import type { Metadata } from "next";
// 暂时禁用Google Fonts以避免Turbopack问题
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MessageBusProvider } from "@/contexts/MessageBusContext";
// Phase 11.4.2: 初始化诊断系统
import "@/lib/core/diagnostic/init";

// 暂时使用系统字体
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: "swap",
//   fallback: ["system-ui", "arial"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   display: "swap",
//   fallback: ["monospace"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className="antialiased">
        <MessageBusProvider>
        {children}
        </MessageBusProvider>
      </body>
    </html>
  );
}
